### ISSUE TITLE
ON button for dimmers

### ISSUE THREAD

**Issue by JoryHogeveen** [kind3r/livolo-rf-codes#3]
A bit related to #1 

When storing the ON button on the switch it stores the actual dim-percentage at the moment of storing.
The actual Livolo remote doesn't work like this. The ON (Toggle) doesn't set a dim-percentage, it just turns the light on at the last dim-percentage when the light was turned off.

**Comment by kind3r** [comment]
The ON and OFF are just scenes (scene 1 and scene 2), they are associated in the switch with the current state of the switch, that's how the Livolo switches work. This is why you have to press on the switch when learning. You put switch in learning mode, you set the switch to desired parameters (ON, OFF etc.) and then you press the remote scene button. The switch will then revert to that state whenever that scene button is pressed.

**Comment by JoryHogeveen** [comment]
Ah check, that clears why it works that way!
